In [1]:
import numpy as np
from scipy import linalg

In [4]:
u = np.array([
    [0, 9, 19, 13], 
    [1, 20, 5, 13],
    [12, 11, 3, 4]
])

v = np.array([
    [2, 0, 0, 0], 
    [1, 2, 2, 0], 
    [2, 1, 1, 0], 
    [0, 0, 1, 1]
])

In [5]:
np.dot(u, v)

array([[47, 37, 50, 13],
       [32, 45, 58, 13],
       [41, 25, 29,  4]])

In [6]:
b = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])
b.mean()

4.875

In [10]:
matr = np.array([[6, 0, 3], [0, -1, 2], [12, 3, 0]])
matr

array([[ 6,  0,  3],
       [ 0, -1,  2],
       [12,  3,  0]])

In [11]:
linalg.det(matr)

0.0

In [12]:
matr1 = np.array([
    [1, -1, -1, 0],
    [-1, 2, -1, -1], 
    [-1, -1, 2, -1],
    [0, -1, -1, 1]
])

In [13]:
linalg.eig(matr1)

(array([-1.+0.j,  1.+0.j,  3.+0.j,  3.+0.j]),
 array([[ 5.00000000e-01,  7.07106781e-01,  5.00000000e-01,
         -8.70388280e-02],
        [ 5.00000000e-01, -1.56125113e-17, -5.00000000e-01,
         -6.09271796e-01],
        [ 5.00000000e-01,  1.50920942e-16, -5.00000000e-01,
          7.83349452e-01],
        [ 5.00000000e-01, -7.07106781e-01,  5.00000000e-01,
         -8.70388280e-02]]))

In [14]:
matr2 = np.array([
    [2,4,0,4,1],
    [2,4,1,1,0],
    [1,1,1,2,2],
    [0,1,3,2,4],
    [2,2,2,0,2]
])

In [15]:
linalg.inv(matr2)

array([[-0.6 ,  0.4 ,  1.6 , -0.6 , -0.1 ],
       [ 0.9 , -0.6 , -1.9 ,  0.4 ,  0.65],
       [-1.7 ,  1.8 ,  2.7 , -0.2 , -1.45],
       [-0.7 ,  0.8 ,  1.7 , -0.2 , -0.95],
       [ 1.4 , -1.6 , -2.4 ,  0.4 ,  1.4 ]])

In [2]:
np.full

<function numpy.full(shape, fill_value, dtype=None, order='C')>

In [3]:
x = np.array([[1,2,3],[6,5,4]]) 

In [8]:
x.reshape((3, -1))

array([[1, 2],
       [3, 6],
       [5, 4]])

In [9]:
x.resize((6, 1))

In [10]:
x

array([[1],
       [2],
       [3],
       [6],
       [5],
       [4]])